### PR TITLE
Add support to other types of tables

### PR DESCRIPTION
**Pull request by Yardanico**
I know that this adds code duplication, but I didn't find a good way of doing it without adding one extra proc.

Also added tests

### CODE REVIEW

**Comment by Yardanico** [comment]
Hm, I think we can remove code duplication for the `toFlatty` proc by doing this:

```nim
proc toFlatty*(s: var string, x: Table | OrderedTable | CountTable) =
  s.addInt64(x.len.int64)
  for k, v in x:
    s.toFlatty(k)
    s.toFlatty(v)
```
Not sure if it would be a good idea to use implicit generics though :)

**Comment by treeform** [comment]
Done: https://github.com/treeform/flatty/commit/d0dc9e5367d2a6037ac5b79cbc8bd4b0be6c249f
I also added support for refs versions.

**Comment by Yardanico** [comment]
@treeform oh, I didn't account for ref versions because I thought that they would be handled like if X is ref: toFlatty(X[]). Thanks :)

**Comment by treeform** [comment]
You are right they actually do! I figured out how to remove code duplication. 

https://github.com/treeform/flatty/commit/0d0ada5b6febb1a1a50b2f9e22f0f6418218fa0f

Thank you for the PR!

**Pull request closed without merging**
